### ISSUE TITLE
Anyone can edit items

### ISSUE THREAD

**Issue by fabianzeiher** [cetceeve/ItemBlocks#10]
- [x] Call ownerOf for NFT in Frontend
- [x] disable edit button if not owner or creator
- [x] add test to confirm bug in smart contract
- [x] add checks to smart contract and confirm correct behavior

**Comment by sifisKoen** [comment]
We solve this issue with a function `isEligible`. This function checks if the user is the `creator` or the `owner` of the item, and if the user is one of them then the function will return `true`. So we use this function to the `updatePassport` function.

**Comment by fabianzeiher** [comment]
finished with testing
