### ISSUE TITLE
Add functionality to transfer ownership

### ISSUE THREAD

**Issue by fabianzeiher** [cetceeve/ItemBlocks#5]
Use the NFT contract to change the ownership of an item

- [x] implement UI button to change ownership
- [x] call change ownership function on contract
- [x] reflect change in the UI

**Comment by fabianzeiher** [comment]
Check out https://docs.etherscan.io if it could be useful.

**Comment by sifisKoen** [comment]
We finished the contract functionality. We created a function `updateOwnership`  where

### First 
We make a check so to see if the array of the hash-map `allItemOwners`   is empty where we store all the owners of the item. Then we just add the user as the first owner of the item.
```solidity
 if (allItemOwners[tokenId].length == 0){
            allItemOwners[tokenId].push(nextOwnerAddress);
```

### Then

If the array of the owners have old users then we call the `safeTransferFrom` function from the **Openzepelin** so to change the ownership of the item (NFT) and then we just add the next owner of the item to the `allItemOwners` hash map, in the array where we store all the owners of the item.

```solidity
else{ 
            safeTransferFrom(currentOwnerAddress, nextOwnerAddress, tokenId);
            allItemOwners[tokenId].push(nextOwnerAddress);
        }
```

**Comment by fabianzeiher** [comment]
Finished UI implementation with #11
