### ISSUE TITLE
Add functionality to track ownership changes

### ISSUE THREAD

**Issue by fabianzeiher** [cetceeve/ItemBlocks#8]
We want to display in our application when and to whom the ownership of the item changed over time.

- [x] Find which events the NFT contract emits for this
- [x] store events
- [x] add ui to show ownership changes

**Comment by fabianzeiher** [comment]
Certainly also possible with alchemy

**Comment by sifisKoen** [comment]
We save the ownership. In the block in a array of owners. Using a hash-map so to make the link between an item and the owners. `{item ID : [users]}`

**Comment by fabianzeiher** [comment]
finished with #11
